# Generated by Django 5.0 on 2023-12-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_film_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='hall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
