# Generated by Django 5.0 on 2023-12-23 19:28

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_film_price_hall_seats_alter_film_hall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
