# Generated by Django 5.0 on 2023-12-23 21:28

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_hall_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='seats',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
