# Generated by Django 5.0 on 2023-12-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_film_timeend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='timeEnd',
            field=models.TimeField(default=models.TimeField()),
        ),
    ]
