# Generated by Django 5.0 on 2023-12-24 19:04

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_film_timeend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='timeEnd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seats',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
