# Generated by Django 5.0 on 2023-12-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_hall_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
