# Generated by Django 5.0 on 2023-12-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_film_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
